name: Test the Lab 1 of Testing
on: push
jobs:
  test-testing-lab1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: bats test
        run: |
          ${GITHUB_WORKSPACE}/test/bats/bin/bats
          ${GITHUB_WORKSPACE}/test/lab-tests.bats
        shell: bash
